name: Check Derived From Main

on:
  pull_request:
    branches: [staging, main]

jobs:
  check-derived-from-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch main
        run: |
          git fetch origin main --depth=1

      - name: Verify the branch is derived from main
        run: |
          COMMIT_SHA_MAIN=$(git rev-parse origin/main)

          COMMIT_SHA_MERGE_BASE=$(git merge-base HEAD origin/main)

          echo "COMMIT_SHA_MAIN:       $COMMIT_SHA_MAIN"
          echo "COMMIT_SHA_MERGE_BASE: $COMMIT_SHA_MERGE_BASE"
          
          echo $(git branch)
          
          if [ "$COMMIT_SHA_MAIN" != "$COMMIT_SHA_MERGE_BASE" ]; then
            echo "ERROR: This branch does NOT include the latest changes from main."
            exit 1
          fi

          echo "SUCCESS: This branch is derived from main."
