name: check-is-based-on-main
on:
  pull_request:
    branches: [staging, main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actual PR commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Fetch origin/main
        run: |
          git fetch origin main

      - name: Compare merge-base
        run: |
          MAIN_SHA=$(git rev-parse origin/main)
          MERGE_BASE=$(git merge-base HEAD origin/main)
          echo "main tip : $MAIN_SHA"
          echo "merge-base: $MERGE_BASE"

          if [ "$MERGE_BASE" != "$MAIN_SHA" ]; then
            echo "PR branch does NOT include the latest main commit."
            exit 1
          fi

          echo "OK: PR branch includes the latest main commit."
