name: check-is-based-on-main
on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # 1. PR の "自動マージ後" ではなく、"実際の PR ブランチ" をチェックアウト
      - name: Checkout actual PR commit
        uses: actions/checkout@v2
        with:
          # pull_request.head.shaを指定すると自動マージ後ではなく本来のPRブランチのHEADになる
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # 2. main の先端を取得
      - name: Fetch origin/main
        run: |
          git fetch origin main

      # 3. merge-base と main の先端 SHA が一致するか確認
      - name: Compare merge-base
        run: |
          MAIN_SHA=$(git rev-parse origin/main)
          MERGE_BASE=$(git merge-base HEAD origin/main)
          echo "main tip : $MAIN_SHA"
          echo "merge-base: $MERGE_BASE"

          if [ "$MERGE_BASE" != "$MAIN_SHA" ]; then
            echo "PR branch does NOT include the latest main commit."
            exit 1
          fi

          echo "OK: PR branch includes the latest main commit."
